chocolate_shop/chocolate_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('', include('products.urls')),
    path('', include('orders.urls')),
    path('', include('orders.urls')),
    path('myauth/', include('shop_auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chocolate_shop/orders/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import *

urlpatterns = [

    path('basket_adding/', basket_adding)

]

chocolate_shop/shop_auth/urls.py
from django.contrib.auth.views import LoginView
from .views import MyLogout, AboutMeView, RegisterView
from django.urls import path

app_name = "myauth"

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'shop_auth/login.html', redirect_authenticated_user=True), name ="login"),
    path('logout/', MyLogout.as_view(), name='logout'),
    path('about-user/', AboutMeView.as_view(), name='about-user'),
    path('register/', RegisterView.as_view(), name='register'),
]

chocolate_shop/shop_auth/models.py
from django.db import models

# Create your models here.

chocolate_shop/shop_auth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, CreateView
from django.urls import reverse, reverse_lazy
from main_page import views

# Create your views here.


class MyLogout(LogoutView):
    next_page = reverse_lazy(views.home)

class AboutMeView(TemplateView):
    template_name = 'shop_auth/about-user.html'

class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'shop_auth/register.html'
    success_url = reverse_lazy('myauth:about-user')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response

chocolate_shop/shop_auth/templates/shop_auth/about-user.html
{% extends 'shop_auth/base.html' %}

{% block title %}
About User
{% endblock %}
{% block body %}
<h1>User info</h1>
{% if user.is_authenticated %}
<h2>Detail</h2>
<p>Username {{user.username}}</p>
<p>First name {{user.first_name}}</p>
<p>Second name {{user.second_name}}</p>
<p>Email {{user.email}}</p>
{% else %}
<h2>User is anon</h2>
{% endif %}
<a href="http://127.0.0.1:8000/"> На главную </a>
<p><a href="{% url 'myauth:logout' %}"> Выйти из профиля </a></p>


{% endblock %}

chocolate_shop/shop_auth/templates/shop_auth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

chocolate_shop/shop_auth/templates/shop_auth/login.html
{% extends 'shop_auth/base.html' %}

{% block title %}
Login
{% endblock %}

{% block body %}
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Login</button>
    </form>
{% endblock %}

chocolate_shop/shop_auth/templates/shop_auth/register.html
{% extends 'shop_auth/base.html' %}

{% block title %}
Регистрация
{% endblock %}

{% block body %}
<h1>Регистрация</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Register">
    </form>
{% endblock %}