chocolate_shop/chocolate_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls')),
    path('', include('products.urls')),
    path('', include('orders.urls')),
    path('', include('orders.urls')),
    path('myauth/', include('shop_auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chocolate_shop/orders/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import *

urlpatterns = [

    path('basket_adding/', basket_adding)

]

chocolate_shop/products/urls.py
from django.urls import path, re_path
from .views import *
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^product/(?P<product_id>\w+)', views.product),
]

chocolate_shop/shop_auth/urls.py
from django.contrib.auth.views import LoginView
from .views import MyLogout, AboutMeView, RegisterView
from django.urls import path

app_name = "myauth"

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'shop_auth/login.html', redirect_authenticated_user=True), name ="login"),
    path('logout/', MyLogout.as_view(), name='logout'),
    path('about-user/', AboutMeView.as_view(), name='about-user'),
    path('register/', RegisterView.as_view(), name='register'),
]

chocolate_shop/products/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'

class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='./products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фото'

chocolate_shop/products/forms.py
# from django import forms
# from .models import *
#
#
# class SubscribersForm(forms.ModelForm):
#     class Meta:
#         model = Subscriber
#         exclude = [""]

chocolate_shop/products/views.py
from django.shortcuts import render
from products.models import *


def product(request, product_id):
    product = Product.objects.get(id=product_id)


    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(request.session.session_key)


    return render(request, 'product.html', locals())

chocolate_shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400" rel="stylesheet">

    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script>    function timeRefresh(time) {
                    setTimeout("location.reload();", 1000);}
    </script>


</head>
<body onload = "timeRefresh()">

    <div class="wrapper">
        <div class="wrapper-content">
            {% include 'navbar.html' %}

            {% block content %}
            {% endblock content %}
        </div>

    </div>

     {% include 'footer.html' %}

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <script src="{% static 'js/scripts.js' %}"></script>

</body>
</html>

chocolate_shop/templates/basket.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="text-center">Товары в корзине</h3>
                <h5 class="text-center">Общая стоимость: {{ request.session.basket.total_amount }} грн </h5>
                        {{ request.session.basket.products }}
                <ul>
                    {% for product in request.session.basket.products %}
                        <li>
                            {{ product.name }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

chocolate_shop/templates/checkout.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row">
            {% if products_in_basket %}
                <div class="col-lg-8 col-lg-offset-2">
                    <h3 class="text-center">Товары в корзине</h3>
                    <h5 class="text-center">Общая стоимость: {{ request.session.basket.total_amount }} грн </h5>
                            {{ request.session.basket.products }}

                    <form class="form-horizontal" method="post">{% csrf_token %}

                            <div class="form-group">
                                <div class="col-lg-4">
                                    <label>Имя</label>
                                    <span class="form-error">{{ form.name.errors }}</span>
                                    <input type="text" name="{{ form.name.html_name }}" class="form-control"
                                        value="{{ request.POST.name }}"
                                    >
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-lg-4">
                                     <label>Телефон</label>
                                     <span class="form-error">{{ form.phone.errors }}</span>
                                    <input type="text" name="{{ form.phone.html_name }}" class="form-control"
                                        value="{{ request.POST.phone }}"
                                    >
                                </div>
                            </div>


                        <table class="table text-center">
                            <thead>
                                <tr>
                                    <th>Название товара</th>
                                    <th>Количество</th>
                                    <th>Цена за еденицу</th>
                                    <th>Общая цена</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product_in_basket in products_in_basket %}
                                    <tr>
                                        <td>
                                             {{ product_in_basket.product.name }}
                                        </td>
                                        <td>
                                             <input value="{{ product_in_basket.nmb }}" type="number"
                                                    class="product-in-basket-nmb" name="product_in_basket_{{ product_in_basket.id }}">
                                        </td>
                                        <td>
                                            <span class="product-price">
                                                {{ product_in_basket.price_per_item}}
                                            </span>
                                        </td>
                                        <td>
                                            <span class="total-product-in-basket-amount">
                                                {{ product_in_basket.total_price }}
                                            </span>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        <div class="text-right">
                            <b>Сумма заказа: </b> <span id="total_order_amount">54</span>
                        </div>

                        <hr>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary btn-lg">Заказать</button>
                        </div>

                    </form>

                </div>
             {% else %}
                <h3 class="text-center">В Вашей корзине нет товаров</h3>
            {% endif %}

        </div>
    </div>
{% endblock %}

chocolate_shop/templates/footer.html
<footer class="footer">
    <div class="container">
        <div class="text">
            <h3>Контакты</h3>
            <p>Тг @typragat</p>
        </div>
    </div>
</footer>

chocolate_shop/templates/happy_face.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Smile</title>
</head>
<body>
<h2>Здравствуйте</h2>
<p>Похоже, какой-то из наших товаров заставил вас улыбнуться, возможно не стоит проходить мимо?)</p>
<button>Купить</button>
<a href="http://127.0.0.1:8000/"> На главную </a>
</body>
</html>

chocolate_shop/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="section-top">
        <img src="{% static 'slider0.png' %}" class="img-responsive">
    </div>
    <div class="section section1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Новые поступления
                    </h1>
                </div>
                {% for product_image in products_images %}
                    {% include 'product_item.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="section section-delivery">
        <div>
            <h3>Товары по категориям</h3>
        </div>
    </div>
    <div class="section section2 phones-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Букеты
                    </h1>
                </div>
                {% for product_image in products_images_phones %}
                    {% include 'product_item.html' %}
                {% endfor %}

            </div>
        </div>
    </div>
    <div class="section section3 laptops-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Елочные игрушки
                    </h1>
                </div>
                {% for product_image in products_images_laptops %}
                    {% include 'product_item.html' %}
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

chocolate_shop/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400" rel="stylesheet">

    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'landing.css' %}">


</head>
<body>

    <div class="general-container">
        <div class="container top-container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1 class="title">Наш магазин скоро откроется!<br>Оставляйте Ваш имейл в форме ниже</h1>
                    <div>
                        <form action="" method="post" class="form form-inline text-center">{% csrf_token %}
                         <div class="form-group">
                             <label>Ваш имейл: </label>
                             <input name="{{ form.email.name }}" class="form-control">
                         </div>
                         <div class="form-group">
                             <label>Ваше имя: </label>
                             <input name="{{ form.name.name }}" class="form-control">
                         </div>
                         <button type="submit" class="btn btn-primary btn-orange">Отправить</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


</body>
</html>

chocolate_shop/templates/navbar.html
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-main">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="">Магазин всякой всячины</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
                    <a href="{% url 'myauth:register' %}"> Регистрация </a>
                    <a href="{% url 'myauth:login' %}"> Вход </a>
            </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

chocolate_shop/templates/product.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item">
                        <img src="{{ image_item.image.url }}" class="img-responsive">
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Price: {{ product.price }}
                    </p>
                </div>
                <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                                Описание
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">
                                Доставка
                            </a>
                        </li>
                        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
                        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content product-description-tabs">
                        <div role="tabpanel" class="tab-pane active" id="description">
                            {{ product.description }}
                        </div>
                        <div role="tabpanel" class="tab-pane" id="delivery">
                            <h3>Как мы делаем доставку</h3>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="messages">...</div>
                        <div role="tabpanel" class="tab-pane" id="settings">...</div>
                      </div>
                </div>
                <div>
                    <form id="form_buying_product" class="form-inline" action="/basket_adding/" method="post">{% csrf_token %}
                        <div class="form-group">
                             <input type="number" class="form-control" name="number" id="number">
                        </div>


                            <div class="form-group">
                                <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                                    data-product_id = "{{ product.id }}"
                                    data-name ="{{ product.name }}"
                                    data-price ="{{ product.price }}"
                                >
                                    Купить
                                </button>
                            </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

chocolate_shop/templates/product_item.html
<div class="col-lg-3">
    <div class="product-item">
        <div>
            <a href="/product/{{ product_image.product.id }}">
                <img src="{{ product_image.image.url }}" class="img-responsive product-photo">
            </a>
        </div>

        {% if product_image.product.discount %}
            <div class="discount-container">
                <span>{{ product_image.product.discount }}%</span>
            </div>
        {% endif %}

        <h4>{{ product_image.product.name }}</h4>
        <p>
            {{ product_image.product.description|truncatechars_html:70 }}
        </p>
        <div>
            {{ product_image.product.price }} UAH
        </div>
        <div class="add-to-card-btn">
            <button class="btn btn-success">
                Добавить в корзину
            </button>
        </div>
    </div>
</div>